module _ChatRoom
{
  typedef sequence<string> stringArr;
  interface Server
  {
    string sayHello();
    oneway void shutdown();
    boolean connect(in string clientName);
    boolean createRoom(in string clientName, in string roomName);
    boolean switchRoom(in string clientName, in string roomName);
    boolean joinRoom(in string clientName, in string roomName);
    boolean leaveRoom(in string clientName, in string roomName);
    void listRoom(in string clientName);
    stringArr retrieve(in string clientName);
    boolean speak(in string clientName, in string message);


  };
};